name: Deploy beta branch to GCF
on:
  push:
    branches:
      - beta
  workflow_dispatch: {}

jobs:
  deploy:
    name: deploy-beta-gcf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Deploy beta to GCF
        run: |
          gcloud functions deploy ${{ github.event.repository.name }}-beta \
            --runtime nodejs16 \
            --memory="128" \
            --region="europe-west3" \
            --allow-unauthenticated \
            --trigger-http \
            --entry-point podletFn \
            --set-env-vars NODE_ENV="production",VERSION="${{ github.sha }}",NAME="${{ github.event.repository.name }}"
      - name: Set authentication
        run: |
          gcloud functions add-iam-policy-binding ${{ github.event.repository.name }}-beta \
            --region="europe-west3" \
            --member="allUsers" \
            --role="roles/cloudfunctions.invoker"
